version: "3.8"

services:
  core:
    network_mode: host
    container_name: core
    image: app:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000
    restart: always
    init: true
