# fly.toml app configuration file generated for monolog-core on 2025-07-31T18:16:50-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'monolog-core'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
