"""add audio processing features

Revision ID: 71d8f7b09521
Revises: 8d10b3b46820
Create Date: 2025-07-30 17:56:58.387989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '71d8f7b09521'
down_revision: Union[str, Sequence[str], None] = '8d10b3b46820'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedbacks', sa.Column('score', sa.Float(), nullable=True))
    op.add_column('feedbacks', sa.Column('audio_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('submissions', sa.Column('transcription', sa.String(), nullable=True))
    op.add_column('submissions', sa.Column('audio_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('submissions', sa.Column('processing_status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'processing_status')
    op.drop_column('submissions', 'audio_metrics')
    op.drop_column('submissions', 'transcription')
    op.drop_column('feedbacks', 'audio_metrics')
    op.drop_column('feedbacks', 'score')
    # ### end Alembic commands ###
