"""update feedback model for structured feedback

Revision ID: be6745fe5ae0
Revises: 71d8f7b09521
Create Date: 2025-07-31 11:43:42.911851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be6745fe5ae0'
down_revision: Union[str, Sequence[str], None] = '71d8f7b09521'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedbacks', sa.Column('structured_feedback', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('feedbacks', sa.Column('overall_performance', sa.String(), nullable=True))
    op.add_column('feedbacks', sa.Column('total_score', sa.Integer(), nullable=True))
    op.add_column('feedbacks', sa.Column('content_alignment_score', sa.Integer(), nullable=True))
    op.add_column('feedbacks', sa.Column('scenario_appropriateness_score', sa.Integer(), nullable=True))
    op.add_column('feedbacks', sa.Column('communication_clarity_score', sa.Integer(), nullable=True))
    op.add_column('feedbacks', sa.Column('audio_delivery_score', sa.Integer(), nullable=True))
    op.drop_column('feedbacks', 'content')
    op.drop_column('feedbacks', 'score')
    op.drop_column('feedbacks', 'audio_metrics')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedbacks', sa.Column('audio_metrics', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('feedbacks', sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('feedbacks', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('feedbacks', 'audio_delivery_score')
    op.drop_column('feedbacks', 'communication_clarity_score')
    op.drop_column('feedbacks', 'scenario_appropriateness_score')
    op.drop_column('feedbacks', 'content_alignment_score')
    op.drop_column('feedbacks', 'total_score')
    op.drop_column('feedbacks', 'overall_performance')
    op.drop_column('feedbacks', 'structured_feedback')
    # ### end Alembic commands ###
